---
title: "Introduction to Psychometrics and Scale Development"
author: "Micah Gerhardt"
date: "12/2/2021"
output: powerpoint_presentation
---


## Introduction
-Psychometrics is a large field that deals with questionnaire development and measurement.

-This presentation is only a small part of what is involved and is focused more on the programming/statistical components

-This is also going to focus on pretty basic concepts

## What is Psychometrics?
-As a field psychometrics is concerned with measurement, testing, and scale development

-This includes concepts such as validity, reliability, and the theory of testing

-Two of the major methods used for scale development are: Factor Analysis and Item Response Theory 

-We will only cover factor analysis today

## History of Factor Analysis
-Developed in 1904 by Charles Spearman to support his hypothesis of intelligence

-Resulted in Spearman's g, a general factor of intelligence

-Intelligence would go on to become a central concept in Psychology 

## History of Factor Analysis (continued)
-Factor analysis would be widely used in a variety of applications and is still one of the most used methods today

-Louis Thurstone would later develop multifactor models and discussed issues such as rotation and simple structure

## What is Factor Analysis?
-Factor analysis is a method of grouping measured variables together by shared variance

-Not enough time to get into the math but there are a number of resources (It is all matrix algebra)

## What is Factor Analysis? (continued)
-In modern day being able to do the matrix algebra by hand isn't that big of a deal. 

-Commonly a 1 time assignment in factor analysis classes to do a simple factor analysis

-Factor analysis involves estimating latent variable(s) from manifest/measured variables 

## Latent Variables
-One can view there being two types of variables: latent variables and manifest or measured variables

-Manifest variables can be directly measured (e.g., Height, blood pressure)

## Latent Variables (continued)

-Latent variables are thought only to exist at a latent level, in psychometrics this often means thoughts, patterns of thinking, mental state, etc.

-Conceptually latent variables exist within the individual and **cause** them to respond to questions in certain manners

## Latent Variables (continued)
-Every latent variable is thought to be normally distributed in the population

-You are likely already familiar with a number of latent variables

-As a side note when estimating these we typically set a mean of 0 and variance of 1

## What isn't Factor Analysis?
-**It is not a principal component analysis**
-The clearest difference is that in PCA the component is a linear combination of the variables

-As stated before factor analysis views the measured variables as resulting from the underlying latent factor

-People often gets PCA confused with factor analysis


## Factor Analysis and Psychometrics
-In psychometrics factor analysis is grouped into two types: Exploratory Factor Analysis (EFA) and Confirmatory Factor Analysis (CFA)

-You will also hear them called unrestricted factor analysis and restricted factor analysis

## Factor Analysis and Psychometrics

-The general process for scale development is:

- <font size="4">Write questions</font>

- <font size="4">Get respondents</font>

- <font size="4">Examine descriptives</font>

- <font size="4">Conduct EFA</font>

- <font size="4">Conduct CFA</font>

-Adjust questions if needed and start again at get respondents step

-New scales typically need to go though this process several times




## CFA
-Now that we have done the EFA we move onto the CFA

-To get out of rotational indeterminacy we restrict paths so that there is a unique best solution

-Will always fit worse than EFA

## Software
-Normally CFA are done in more specialized software

-psych package is installed on the server here

-The package, lavaan, I will use from this point on is not

-lavaan is a super useful package and comparable software is often $500+ a year for a personal license


## Topics if we have time

## More Advanced Topics

-Another important aspect of scale development is measurement invariance

-Many scales will have EFA and CFA done on them in development, although many don't reach this bar

-Fewer scales are examined for measurement invariance

## More Advanced Topics (continued)

-Explained simply the idea is that there are aspects that we don't want to effect the responses differently, often across classes

-Some common areas to examine measurement invariance are sex, race, and age

## Measurement Invariance

-To test measurement invariance we set up increasingly restrictive models and examine if model fit is significantly worse

-There are four levels of invariance testing, although only the first 3 need to be passed for a scale to demonstrate measurement invariance

## Measurement Invariance (continued)

-Configural (same factor structure)

-Metric (Same factor loadings)

-Scalar (Same intercepts)

-Strict (same error variances)

-Scales that fail to reach scalar are considered non-invariant

## Final Topic- SEM
-Now that you have latent variables that you feel good about what should you do?

-Often want to use in a model to predict some outcome.

-Structural Equation Modeling (SEM) is a covariance model

-Has two portions, the measurement model, what we have been doing, and the structural model

-Structural part is similar to a regression

